apiVersion: v1
kind: ServiceAccount
metadata:
  name: flask-sa
automountServiceAccountToken: false

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-sa
automountServiceAccountToken: false
